### PR TITLE
Feature/english dotenv

### PR DESCRIPTION
**Pull request by funkatron**
translate to English, use .env file

### CODE REVIEW

**Comment by funkatron** [comment]
Mistakenly opened a PR here for changes I didn't intend to push back. May in future though.

**Comment by lucasmezencio** [comment]
@funkatron :(

**Comment by jgrossi** [comment]
@funkatron you're welcome :-)

**Comment by funkatron** [comment]
I didn't because I'm hacking something together quickly, but the changes I made would mostly merge fine. The only issue would be handling translations properly -- I just edited the twig file directly, but really there should be proper I10N being done. If you want to see, look at https://github.com/phpmg/slack-invitation/compare/master...funkatron:master

**Pull request closed without merging**
